### ISSUE TITLE
Feature Request: show current URL

### ISSUE THREAD

**Issue by mmmeff** [andrewburgess/datscool#5]
Display current URL w/ easy "open in another tab" functionality.

This should be handy - I've seen a few dat sites bug out when in an iframe. Not sure why/didn't investigate, but it would be good to have an escape hatch when crap happens.

**Comment by andrewburgess** [comment]
Note: `iframe` bug outs seem to be related to https://github.com/beakerbrowser/beaker/issues/863

Essentially, the beaker/dat/experimental APIs aren't exposed in `iframe`s
